# Generated by Django 5.1.3 on 2024-11-23 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameModel",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("status", models.IntegerField(default=0)),
                ("created_by", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "Games",
            },
        ),
        migrations.CreateModel(
            name="PlayerModel",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_connected", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gameId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="games_app.gamemodel",
                    ),
                ),
            ],
            options={
                "db_table": "Players",
            },
        ),
        migrations.CreateModel(
            name="ScoreModel",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gameId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="games_app.gamemodel",
                    ),
                ),
                (
                    "playerId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="games_app.playermodel",
                    ),
                ),
            ],
            options={
                "db_table": "Scores",
            },
        ),
    ]
