# Generated by Django 5.1.3 on 2024-11-24 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games_app", "0002_gamemodel_roomid_playermodel_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playermodel",
            name="gameId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="games_app.gamemodel",
            ),
        ),
    ]
