# Generated by Django 5.1.3 on 2024-11-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games_app", "0004_playermodel_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="playermodel",
            name="win",
            field=models.IntegerField(default=0),
        ),
    ]
