# Generated by Django 5.1.3 on 2024-11-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games_app", "0005_playermodel_win"),
    ]

    operations = [
        migrations.AddField(
            model_name="playermodel",
            name="name",
            field=models.CharField(default="Anonymous", max_length=100),
        ),
    ]
