# Generated by Django 5.1.3 on 2024-12-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games_app", "0006_playermodel_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamemodel",
            name="isSinglePlayer",
            field=models.BooleanField(default=False),
        ),
    ]
