# Generated by Django 5.1.3 on 2024-12-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games_app", "0007_gamemodel_issingleplayer"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamemodel",
            name="matchId",
            field=models.CharField(default="123", max_length=64),
            preserve_default=False,
        ),
    ]
