# Generated by Django 5.1.3 on 2024-12-19 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_app', '0008_gamemodel_matchid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoremodel',
            name='gameId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='games_app.gamemodel'),
        ),
        migrations.AlterField(
            model_name='scoremodel',
            name='playerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='games_app.playermodel'),
        ),
    ]
